### ISSUE TITLE
Add integration testing to Travis CI

### ISSUE THREAD

**Issue by mitchute** [mitchute/GLHE#1]
Not sure how, but probably should add another environment to run integration tests. I'm not sure ```nose``` is the right tool for this, though.

Thoughts, @myoldmopar?

**Comment by Myoldmopar** [comment]
I think nose might be fine for this, depending on how the integration command is executed.  Nose will just sniff around and find and execute all the unit tests.  So if you can create your own unit test class and functions that then execute integration runs and validate outputs, nose will work great.

**Comment by mitchute** [comment]
"nose"... "sniff around"... nice.

So that will be another python env, but the commands will not call setup now, right?

**Comment by Myoldmopar** [comment]
Sorry we didn't make it to this topic when we talked.  Yeah, nose is appropriately named as it really just sniffs out unit tests and runs them.  As for nomenclature, I'm not sure about it being another Python env, in the sense that I'm used to the word env.  When I think of env, I think of how tox creates isolated Python environments, each with their own packages, so that system packages don't intermingle with the test environment.  In this case, I'm just talking about adding yet another regular old unit test that will simply run an integration file and have some assertions.  Nose is typically executed as a setup.py call, so you wouldn't also want those unit tests calling setup.py to run the integration tests.

Aaaand I'm rambling.  Let's talk tomorrow if you'd like.

**Comment by mitchute** [comment]
I was just thinking that it would be nice to have the integration run separately from the unit tests on Travis. Probably not necessary at this point though.
